"""Statische Demo-/Test-Falldaten fuer SeedService.create_seed_cases().

Ausgelagert aus seed_service.py (Refactoring): Diese eine Liste machte gut
400 der 797 Zeilen der Datei aus - reine Daten, keine Logik. build_seed_cases()
liefert exakt dieselben Case-Objekte wie zuvor inline in create_seed_cases()
konstruiert. Das Scoring (ScoringService.update_case_scoring) und das Setzen
von is_demo_data=True bleiben bewusst in seed_service.py, da das Verhalten
(nicht nur Daten) ist.
"""
from models.case import Case, CaseCustomer, Classification, WorkflowStatus, TimelineEntry
from enums import BoardColumn, Actor, Channel


def build_seed_cases() -> list[Case]:
    from services.i18n_service import tr

    cases = [
        Case(
            case_id="T-2026-0001",
            created_at="2026-08-23T09:15:00",
            updated_at="2026-08-23T14:30:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10482",
                practice_name="Gemeinschaftspraxis Dr. Müller & Partner",
                is_vip=True,
                contact_person="Frau Weber",
                phone="+49 731 123456-12",
            ),
            classification=Classification(
                schema_id="schema_zuzahlungsnachforderung",
                title=tr("demo_cases.c1_title", "Zuzahlungsnachforderungsdatei fehlerhaft erzeugt"),
                deadline_callback="2026-08-23T16:00:00",
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.ACTION_REQUIRED,
                current_actor=Actor.DEVELOPMENT,
                actor_since="2026-08-23T10:00:00",
            ),
            form_data={
                "action_type": "Zuzahlungsnachforderung",
                "invoice_number": "RE-2026-0815",
                "invoice_date": "2026-08-01",
                "prescription_info": "VO-987654 (Physiotherapie)",
                "prescription_date": "2026-07-15",
                "patient_names": "Max Mustermann, Maria Muster",
                "esol_filename": "ESOL_20260801_Praxis.dat",
                "action_reason_detail": "Nachforderung von 14 Zuzahlungsbeträgen nach Abrechnungskorrektur.",
                "has_forwarded_email_or_screenshot": True,
            },
            missing_required_fields=[],
            attachment_directory="attachments/T-2026-0001_Gemeinschaftspraxis_Dr_Mueller/",
            timeline=[
                TimelineEntry(
                    timestamp="2026-08-23T09:15:00",
                    author="Daniel Rösch",
                    channel=Channel.PHONE_INBOUND,
                    note="Praxis meldet Abbruch beim Erzeugen der Zuzahlungsdatei. Rückruf bis 16:00 versprochen.",
                    status_change="NEW -> ACTION_REQUIRED (SUPPORT)",
                ),
                TimelineEntry(
                    timestamp="2026-08-23T10:00:00",
                    author="Daniel Rösch",
                    channel=Channel.DEV_TICKET,
                    note="Ticket via GitLab-Template an Dev übergeben. Warte auf Prüfung der Abrechnungs-Engine.",
                    status_change="ACTION_REQUIRED (SUPPORT) -> ACTION_REQUIRED (DEVELOPMENT)",
                ),
            ],
        ),
        Case(
            case_id="T-2026-0002",
            created_at="2026-08-20T11:00:00",
            updated_at="2026-08-20T11:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10890",
                practice_name="Praxisklinik am Stadtgarten",
                is_vip=True,
                contact_person="Dr. Elena Rossi",
                phone="+49 89 987654-0",
            ),
            classification=Classification(
                schema_id="schema_bug_report",
                title=tr("demo_cases.c2_title", "Absturz beim Drucken von BMA-Rezepten"),
                deadline_callback="2026-08-21T10:00:00",  # Overdue
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.ACTION_REQUIRED,
                current_actor=Actor.SUPPORT,
                actor_since="2026-08-20T11:00:00",
                is_data_complete=True,
            ),
            form_data={
                "module_name": "Rezeptdruck",
                "reproduction_steps": "Drucken -> BMA auswählen -> Vorschau klicken",
                "stack_trace": "Access Violation at 0x0045A1",
            },
            missing_required_fields=[],
            attachment_directory="attachments/T-2026-0002_Praxisklinik_Stadtgarten/",
            timeline=[
                TimelineEntry(timestamp="2026-08-20T11:00:00", author="Daniel Rösch", note="Rezeptdruck stürzt ab"),
            ],
        ),
        Case(
            case_id="T-2026-0003",
            created_at="2026-08-23T12:00:00",
            updated_at="2026-08-23T12:00:00",
            created_by="Max Müller",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10211",
                practice_name="Zahnarztpraxis Dr. Schmidt",
                is_vip=False,
                contact_person="Herr Schmidt",
                phone="+49 30 5551234",
            ),
            classification=Classification(
                schema_id="schema_abrechnungskorrektur",
                title=tr("demo_cases.c3_title", "KV-Abrechnungstext korrigieren"),
                deadline_callback="",
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.NEW,
                current_actor=Actor.SUPPORT,
                actor_since="2026-08-23T12:00:00",
                is_data_complete=True,
            ),
            form_data={"kv_region": "KV Berlin", "correction_reason": "Falsche KV-Nummer"},
            missing_required_fields=[],
            attachment_directory="attachments/T-2026-0003_Zahnarztpraxis_Schmidt/",
            timeline=[TimelineEntry(timestamp="2026-08-23T12:00:00", author="Max Müller", note="Anfrage zur Korrektur")],
        ),
        Case(
            case_id="T-2026-0004",
            created_at="2026-08-22T15:00:00",
            updated_at="2026-08-22T15:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10554",
                practice_name="MVZ Kardiologie Rhein-Neckar",
                is_vip=False,
                contact_person="Klaus Becker",
                phone="+49 621 443322",
            ),
            classification=Classification(
                schema_id="schema_zuzahlungsnachforderung",
                title=tr("demo_cases.c4_title", "Prüfung Nachforderung 2026-Q1"),
                deadline_callback="",
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.WAITING,
                current_actor=Actor.CUSTOMER,
                actor_since="2026-08-22T15:00:00",
                is_data_complete=False,
            ),
            form_data={"billing_quarter": "2026-Q1", "error_code": "ERR_CHECK_04"},
            missing_required_fields=["database_dump_provided"],
            attachment_directory="attachments/T-2026-0004_MVZ_Kardiologie/",
            timeline=[TimelineEntry(timestamp="2026-08-22T15:00:00", author="Daniel Rösch", note="Warten auf DB-Dump der Praxis")],
        ),
        Case(
            case_id="T-2026-0005",
            created_at="2026-08-23T13:00:00",
            updated_at="2026-08-23T13:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10777",
                practice_name="Hausarztpraxis Dipl.-Med. Fischer",
                is_vip=False,
                contact_person="Dipl.-Med. Fischer",
                phone="+49 341 889900",
            ),
            classification=Classification(
                schema_id="schema_bug_report",
                title=tr("demo_cases.c5_title", "GUI-Schriftgröße im Laborfenster zu klein"),
                deadline_callback="",
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.NEW,
                current_actor=Actor.SUPPORT,
                actor_since="2026-08-23T13:00:00",
                is_data_complete=True,
            ),
            form_data={"module_name": "Labor", "reproduction_steps": "Laborblatt öffnen auf 4K Monitor"},
            missing_required_fields=[],
            attachment_directory="attachments/T-2026-0005_Hausarztpraxis_Fischer/",
            timeline=[TimelineEntry(timestamp="2026-08-23T13:00:00", author="Daniel Rösch", note="Feedback erfasst")],
        ),
        Case(
            case_id="T-2026-0006",
            created_at="2026-08-15T08:00:00",
            updated_at="2026-08-16T10:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10482",
                practice_name="Gemeinschaftspraxis Dr. Müller & Partner",
                is_vip=True,
            ),
            classification=Classification(
                schema_id="schema_abrechnungskorrektur",
                title="Alte Abrechnung Q1 gelöst",
                deadline_callback="",
            ),
            workflow_status=WorkflowStatus(
                is_completed=True,
                is_archived=False,
                board_column=BoardColumn.DONE,
                current_actor=Actor.SUPPORT,
                actor_since="2026-08-16T10:00:00",
                is_data_complete=True,
            ),
            form_data={"kv_region": "KV BW", "correction_reason": "Korrektur abgeschlossen"},
            missing_required_fields=[],
            attachment_directory="attachments/T-2026-0006_Gemeinschaftspraxis_Dr_Mueller/",
            timeline=[TimelineEntry(timestamp="2026-08-16T10:00:00", author="Daniel Rösch", note="Erfolgreich abgeschlossen")],
        ),
        Case(
            case_id="T-2026-0007",
            created_at="2026-07-01T09:00:00",
            updated_at="2026-07-05T12:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10890",
                practice_name="Praxisklinik am Stadtgarten",
                is_vip=True,
            ),
            classification=Classification(
                schema_id="schema_bug_report",
                title="Uralter Fall aus dem Vormonat",
                deadline_callback="",
            ),
            workflow_status=WorkflowStatus(
                is_completed=True,
                is_archived=False,
                board_column=BoardColumn.DONE,
                current_actor=Actor.SUPPORT,
                actor_since="2026-07-05T12:00:00",
                is_data_complete=True,
            ),
            form_data={"module_name": "System", "reproduction_steps": "Behoben"},
            missing_required_fields=[],
            attachment_directory="attachments/T-2026-0007_Praxisklinik_Stadtgarten/",
            timeline=[TimelineEntry(timestamp="2026-07-05T12:00:00", author="Daniel Rösch", note="Geklärt")],
        ),
        Case(
            case_id="T-2026-0008",
            created_at="2026-08-23T14:00:00",
            updated_at="2026-08-23T14:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10211",
                practice_name="Zahnarztpraxis Dr. Schmidt",
                is_vip=False,
            ),
            classification=Classification(
                schema_id="schema_zuzahlungsnachforderung",
                title="Frische Nachforderung ohne DB-Dump",
                deadline_callback="2026-08-23T18:00:00",
                tags=["Abrechnung", "Nachforderung"],
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.ACTION_REQUIRED,
                current_actor=Actor.SUPPORT,
                actor_since="2026-08-23T14:00:00",
                is_data_complete=False,
            ),
            form_data={"action_type": "Zuzahlungsnachforderung", "invoice_number": "RE-999"},
            missing_required_fields=["prescription_info"],
            attachment_directory="attachments/T-2026-0008_Zahnarztpraxis_Schmidt/",
            timeline=[TimelineEntry(timestamp="2026-08-23T14:00:00", author="Daniel Rösch", note="Neu erfasst")],
        ),
        Case(
            case_id="T-2026-0009",
            created_at="2026-08-22T08:30:00",
            updated_at="2026-08-23T11:00:00",
            created_by="Max Müller",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10482",
                practice_name="Gemeinschaftspraxis Dr. Müller & Partner",
                is_vip=True,
                contact_person="Dr. Müller",
            ),
            classification=Classification(
                schema_id="schema_feature_request",
                title="Kundenwunsch: Schnell-Button für eRezept-Export",
                tags=["Kundenwunsch", "eRezept", "VIP"],
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.IN_PROGRESS,
                current_actor=Actor.DEVELOPMENT,
                actor_since="2026-08-22T10:00:00",
                followup_at="2026-08-25T09:00:00",
                followup_note="Beim Dev-Team nach Sprint-Einplanung fragen",
                is_data_complete=True,
            ),
            form_data={
                "module_name": "eRezept / Verordnung",
                "feature_description": "Praxis wünscht sich 1-Klick-Button in der Patientenakte.",
                "practice_benefit": "Zeitersparnis von ca. 30 Min pro Tag bei Rezeptausgabe.",
                "has_mockup_or_screenshot": True,
            },
            attachment_directory="attachments/T-2026-0009_Feature_eRezept/",
            timeline=[
                TimelineEntry(timestamp="2026-08-22T08:30:00", author="Max Müller", note="Kundenwunsch am Telefon erfasst"),
                TimelineEntry(timestamp="2026-08-22T10:00:00", author="Daniel Rösch", note="An Produktmanagement/Dev übergeben", status_change="ZUSTÄNDIGKEIT: Support -> Entwicklung"),
            ],
        ),
        Case(
            case_id="T-2026-0010",
            created_at="2026-08-23T15:20:00",
            updated_at="2026-08-23T15:20:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10554",
                practice_name="MVZ Kardiologie Rhein-Neckar",
                is_vip=False,
                contact_person="Klaus Becker",
            ),
            classification=Classification(
                schema_id="schema_bug_report",
                title="Kartenleser-Treiber nach Windows-Update getrennt",
                tags=["Hardware", "Treiber"],
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.ACTION_REQUIRED,
                current_actor=Actor.TECH,
                actor_since="2026-08-23T15:20:00",
                followup_at="2026-08-24T10:00:00",
                followup_note="Fernwartung mit IT-Admin Becker durchführen",
                is_data_complete=True,
            ),
            form_data={
                "module_name": "EGK-Kartenleser",
                "error_message": "DEVICE_NOT_FOUND (Code 43)",
                "reproduction_steps": "Leser an USB 3.0 anschließen -> Dienst startet nicht",
                "database_dump_provided": False,
            },
            attachment_directory="attachments/T-2026-0010_Kartenleser/",
            timeline=[TimelineEntry(timestamp="2026-08-23T15:20:00", author="Daniel Rösch", note="Fernwartungs-Termin vereinbart")],
        ),
        Case(
            case_id="T-2026-0011",
            created_at="2026-08-01T10:00:00",
            updated_at="2026-08-02T12:00:00",
            created_by="Daniel Rösch",
            assigned_to="Daniel Rösch",
            customer=CaseCustomer(
                customer_id="K-10777",
                practice_name="Hausarztpraxis Dipl.-Med. Fischer",
                is_vip=False,
            ),
            classification=Classification(
                schema_id="schema_zuzahlungsnachforderung",
                title="Alte Nachforderung aus Vorquartal (Archiviert)",
                tags=["Archiv"],
            ),
            workflow_status=WorkflowStatus(
                is_completed=True,
                is_archived=True,
                board_column=BoardColumn.DONE,
                current_actor=Actor.SUPPORT,
                actor_since="2026-08-02T12:00:00",
                is_data_complete=True,
            ),
            form_data={"action_type": "Zuzahlungsnachforderung", "invoice_number": "RE-OLD-01"},
            attachment_directory="attachments/T-2026-0011_Archiv/",
            timeline=[TimelineEntry(timestamp="2026-08-02T12:00:00", author="Daniel Rösch", note="Fall abgeschlossen und archiviert")],
        ),
        Case(
            case_id="T-2026-0012",
            created_at="2026-08-23T16:00:00",
            updated_at="2026-08-23T16:00:00",
            created_by="Max Müller",
            assigned_to="Max Müller",
            customer=CaseCustomer(
                customer_id="K-10890",
                practice_name="Praxisklinik am Stadtgarten",
                is_vip=True,
            ),
            classification=Classification(
                schema_id="schema_bug_report",
                title="Absturz bei PVS-GKV Abrechnungsexport",
                deadline_callback="2026-08-23T17:30:00",  # Overdue
                tags=["Dringend", "VIP", "Absturz"],
            ),
            workflow_status=WorkflowStatus(
                is_completed=False,
                is_archived=False,
                board_column=BoardColumn.ACTION_REQUIRED,
                current_actor=Actor.DEVELOPMENT,
                actor_since="2026-08-23T16:00:00",
                is_data_complete=False,
            ),
            form_data={"module_name": "GKV-Export", "error_message": "ERR_ACCESS_VIOLATION_0x00FF"},
            missing_required_fields=["reproduction_steps", "database_dump_provided"],
            attachment_directory="attachments/T-2026-0012_Absturz_PVS/",
            timeline=[TimelineEntry(timestamp="2026-08-23T16:00:00", author="Max Müller", note="Kritischer Fehler bei Abrechnung")],
        ),
    ]
    return cases
