from typing import Any, Callable, Optional

class MenuItem:
    def __init__(self, text: str, action: Callable[..., Any], **kwargs: Any) -> None: ...

class Menu:
    SEPARATOR: Any
    def __init__(self, *items: Any) -> None: ...

class Icon:
    icon: Any
    title: str
    menu: Any
    def __init__(self, name: str, icon: Any = ..., title: str = ..., menu: Any = ..., **kwargs: Any) -> None: ...
    def run(self, setup: Optional[Callable[..., Any]] = None) -> None: ...
    def stop(self) -> None: ...
    def visible(self) -> bool: ...
