from typing import Any, Optional

class Template:
    def __init__(self, source: str, **kwargs: Any) -> None: ...
    def render(self, *args: Any, **kwargs: Any) -> str: ...

class Environment:
    def __init__(self, **kwargs: Any) -> None: ...
    def from_string(self, source: str) -> Template: ...
