from typing import Any, Callable, Optional

def fixture(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def mark(*args: Any, **kwargs: Any) -> Any: ...
def raises(*args: Any, **kwargs: Any) -> Any: ...
