from typing import Any, Callable, Optional

def fixture(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def mark(*args: Any, **kwargs: Any) -> Any: ...
def raises(*args: Any, **kwargs: Any) -> Any: ...
def skip(*args: Any, **kwargs: Any) -> Any: ...
def fail(*args: Any, **kwargs: Any) -> Any: ...
def param(*args: Any, **kwargs: Any) -> Any: ...
def importorskip(*args: Any, **kwargs: Any) -> Any: ...

class MonkeyPatch:
    def __init__(self) -> None: ...
    def setattr(self, target: Any, name: Any, value: Any = ..., raising: bool = ...) -> None: ...
    def delattr(self, target: Any, name: Any = ..., raising: bool = ...) -> None: ...
    def setitem(self, dic: Any, name: Any, value: Any) -> None: ...
    def delitem(self, dic: Any, name: Any, raising: bool = ...) -> None: ...
    def setenv(self, name: str, value: str, prepend: Optional[str] = ...) -> None: ...
    def delenv(self, name: str, raising: bool = ...) -> None: ...
    def syspath_prepend(self, path: Any) -> None: ...
    def chdir(self, path: Any) -> None: ...
    def undo(self) -> None: ...

