from typing import Any, Callable, Sequence, Union, Tuple, Optional
import tkinter as tk

def set_appearance_mode(mode_string: str) -> None: ...
def get_appearance_mode() -> str: ...
def set_default_color_theme(color_string: str) -> None: ...

class CTkFont:
    def __init__(
        self,
        family: Optional[str] = ...,
        size: Optional[int] = ...,
        weight: Optional[str] = ...,
        slant: Optional[str] = ...,
        underline: Optional[bool] = ...,
        overstrike: Optional[bool] = ...,
    ) -> None: ...

class CTk(tk.Tk):
    def __init__(self, fg_color: Optional[Union[str, Tuple[str, str]]] = ..., **kwargs: Any) -> None: ...
    def mainloop(self, n: int = 0) -> None: ...
    def destroy(self) -> None: ...
    def title(self, string: Optional[str] = None) -> str: ...
    def geometry(self, newGeometry: Optional[str] = None) -> str: ...
    def minsize(self, width: Optional[int] = None, height: Optional[int] = None) -> Tuple[int, int]: ...
    def maxsize(self, width: Optional[int] = None, height: Optional[int] = None) -> Tuple[int, int]: ...
    def resizable(self, width: Optional[bool] = None, height: Optional[bool] = None) -> Tuple[bool, bool]: ...
    def protocol(self, name: Optional[str] = None, func: Optional[Callable[..., Any]] = None) -> Any: ...
    def after(self, ms: int, func: Optional[Callable[..., Any]] = None, *args: Any) -> str: ...

class CTkToplevel(tk.Toplevel):
    def __init__(self, master: Any = None, **kwargs: Any) -> None: ...
    def title(self, string: Optional[str] = None) -> str: ...
    def geometry(self, newGeometry: Optional[str] = None) -> str: ...
    def resizable(self, width: Optional[bool] = None, height: Optional[bool] = None) -> Tuple[bool, bool]: ...
    def grab_set(self) -> None: ...
    def destroy(self) -> None: ...

class CTkFrame(tk.Frame):
    def __init__(self, master: Any = None, width: int = ..., height: int = ..., corner_radius: Optional[int] = ..., border_width: Optional[int] = ..., bg_color: Union[str, Tuple[str, str]] = ..., fg_color: Union[str, Tuple[str, str]] = ..., border_color: Union[str, Tuple[str, str]] = ..., cursor: str = ..., **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def pack_forget(self) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def winfo_children(self) -> Sequence[Any]: ...

class CTkScrollableFrame(CTkFrame):
    def __init__(self, master: Any = None, **kwargs: Any) -> None: ...

class CTkLabel(tk.Label):
    def __init__(self, master: Any = None, text: str = ..., font: Optional[Any] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., anchor: str = ..., justify: str = ..., wraplength: int = ..., width: int = ..., height: int = ..., **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class CTkButton(tk.Button):
    def __init__(self, master: Any = None, text: str = ..., command: Optional[Callable[..., Any]] = ..., width: int = ..., height: int = ..., fg_color: Optional[Union[str, Tuple[str, str]]] = ..., hover_color: Optional[Union[str, Tuple[str, str]]] = ..., text_color: Optional[Union[str, Tuple[str, str]]] = ..., state: str = ..., **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class CTkEntry(tk.Entry):
    def __init__(self, master: Any = None, placeholder_text: str = ..., width: int = ..., height: int = ..., border_color: Optional[Union[str, Tuple[str, str]]] = ..., border_width: int = ..., **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def insert(self, index: Union[int, str], string: str) -> None: ...
    def delete(self, first: Union[int, str], last: Optional[Union[int, str]] = None) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class CTkTextbox(tk.Text):
    def __init__(self, master: Any = None, width: int = ..., height: int = ..., **kwargs: Any) -> None: ...
    def get(self, index1: str, index2: Optional[str] = None) -> str: ...
    def insert(self, index: str, chars: str, *args: Any) -> None: ...
    def delete(self, index1: str, index2: Optional[str] = None) -> None: ...

class CTkCheckBox(tk.Checkbutton):
    def __init__(self, master: Any = None, text: str = ..., variable: Optional[Any] = ..., command: Optional[Callable[..., Any]] = ..., width: int = ..., height: int = ..., **kwargs: Any) -> None: ...
    def get(self) -> int: ...
    def configure(self, **kwargs: Any) -> None: ...

class CTkOptionMenu(tk.OptionMenu):
    def __init__(self, master: Any = None, values: Sequence[str] = ..., command: Optional[Callable[[str], Any]] = ..., width: int = ..., height: int = ..., **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def set(self, value: str) -> None: ...
    def cget(self, key: str) -> Any: ...
    def configure(self, **kwargs: Any) -> None: ...

class CTkTabview(CTkFrame):
    def __init__(self, master: Any = None, **kwargs: Any) -> None: ...
    def add(self, name: str) -> CTkFrame: ...
    def set(self, name: str) -> None: ...

class CTkInputDialog(CTkToplevel):
    def __init__(self, master: Any = None, text: str = ..., title: str = ..., **kwargs: Any) -> None: ...
    def get_input(self) -> Optional[str]: ...

BooleanVar = tk.BooleanVar
StringVar = tk.StringVar
IntVar = tk.IntVar
DoubleVar = tk.DoubleVar
